name: Weekly News

on:
  workflow_dispatch:

  schedule:
    - cron: '0 5 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install feedparser

      - name: Generate report
        run: |
          python scripts/fetch_news.py

      - name: Save report to repository
        run: |
          mkdir -p reports
          cp weekly_report.md reports/$(date +%F).md
          
      - name: Generate website index
        run: |
          python scripts/generate_index.py
          
      - name: Commit report
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          git add reports/
          git add index.html

          git commit -m "Weekly report $(date +%F)" || exit 0
          git push

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: weekly-report
          path: weekly_report.md
